FRONTENDBOOTCAMP-13th/12zizo

- src/components/login-input.html
- input 요소로 input 컴포넌트 생성
- input 컴포넌트에는 label, input, button이 포함되어 있음
Resolves #2
resolves #2
> 🎨 Feat: 로그인 인풋 컴포넌트 생성

- src/style.css
- 브레이크포인트 변수 생성
- 브랜드 컬러 변수 생성
Resolves #10
필요한 기본적인 색상, 브레이크 포인트 변수를 생성했습니다.
resolves #10
> 🐳 Chore: 기본 변수 세팅

- src/components/login-button.html
- 속성 순서 변경
- 코드 보기 쉽게 줄넘김
- px 단위 rem으로 변경
- 색상코드 테일윈드 기본 변수로 변경
Resolves #15
코드 규칙에 맞게 수정완료했습니다.
resolves #15
> 💄 Style: 규칙에 맞게 로그인 버튼 컴포넌트 코드 수정

- src/components/footer.html
- 속성 순서 변경
- 코드 보기 쉽게 줄넘김
- span 태그 내부를 a태그로 래핑하여 클릭 가능한 요소로 변경
Resolves #13
- [V] 새로운 기능 추가
- [V] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [V] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [V] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #13
> 💄 Style: 규칙에 맞게 footer 컴포넌트 코드 수정

- src/components/login-input.html
> 💄 Style: 규칙에 맞게 로그인 인풋 컴포넌트 코드 수정

- src/style.css
- gray 색상 변수 수정
- 배경 색상 변수 추가
Resolves #20
회색 색상이 기존 시간과 다르다고 하여서 초기화하고 새로 변수를 등록했습니다.
배경 색상을 추가했습니다.
resolves #20
> 🐳 Chore: 색상 변수 추가

- index.html
- src/components/image-carousel.html
- src/components/logout.html
- src/components/modal.html
- src/components/profile-change.html
- src/components/search.html
- src/components/transparent-button.html
- 이미지 캐러셀 컴포넌트
- 로그아웃 컴포넌트
- 모달 컴포넌트
- 프로필 전환 컴포넌트
- 검색 컴포넌트
- 투명 버튼 컴포넌트
- [V] 파일 혹은 폴더명 수정
- [V] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [V] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #23
> 🐳 chore: 컴포넌트 생성을 위한 페이지 생성

- index.html
- src/components/image-carousel.html
- src/style.css
- [V] 새로운 기능 추가
- [V] 버그 수정
- [V] CSS 등 사용자 UI 디자인 변경
- [V] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [V] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #27
> ✨ Feat: 검색 페이지 컴포넌트 생성 💄 style: CSS 등 사용자 UI 디자인 변경 🐛 fix: 버그, 오류 수정 

- src/components/search.html
- 검색 input 컴포넌트 생성
- 랭킹 버튼 컴포넌트 생성
- 최근 검색어 버튼 컴포넌트 생성
- 최근 검색어 지우기 버튼 컴포넌트 생성
Resolves #26
검색 페이지에 필요한 컴포넌트를 생성했습니다.
resolves #26
> 🎨 Feat: 검색 페이지 컴포넌트 생성

- src/components/logout.html
확인 취소 버튼에 hover 속성을 추가했습니다.
resolves #32
> Feat/logout modal component/jinhyun

- src/components/transparent-button.html
> 🎨Feat: 투명 버튼 및 일시정지,재생 버튼 컴포넌트

- src/components/modal.html
- 모달 창 생성
Resolves #39
resolves #39
> 🎨 Feat: 교육용 페이지 안내 모달창 컴포넌트 생성

- index.html
- src/components/common-image-carousel.html
- 공통 이미지 캐러셀을 위한 index.html 경로 설정
- 공통 이미지 캐러셀 flex container로 생성
resolves #37
> ✨ feat: 기능 추가, 변경

- src/components/login-input.html
- 아이디, 비밀번호 입력창 수정
- 비밀번호 토글 버튼 생성
- 오류메세지 출력창 생성
resolves #29
> 💄 Style : 로그인 인풋 컴포넌트 수정

- src/components/live-ranking-component.html
> Feat/live ranking component/jinhyun

- index.html
- src/components/common-image-carousel.html
- src/components/footer.html
- src/components/header.html
- src/components/image-carousel.html
- src/components/live-ranking-component.html
- src/components/login-button.html
- src/components/login-input.html
- src/components/logout.html
- src/components/modal.html
- src/components/original.html
- src/components/profile-change.html
- src/components/search.html
- src/components/top20-image-carousel.html
- src/components/transparent-button.html
> 💄index파일에 a태그 추가 및 컴포넌트 title 수정

- src/pages/join-in.html
> 🎨 Feat: 회원가입 페이지 생성

- src/pages/login.html
> 로그인 페이지 수정

- src/pages/join-in-page.html
- 아이디, 비밀번호 에러메세지 추가
- 접근성 관리
resolves #86
> 회원가입 페이지 수정

- src/pages/id-search.html
> 아이디 찾기 페이지 수정

- src/pages/password-search.html
- aria-label, tabindex등 접근성 관련 속성 추가
resolves #80
> 💄비밀번호 찾기 페이지 접근성 관련 코드 추가

- src/pages/id-search.html
- src/pages/join-in-page.html
- src/pages/login.html
- src/pages/password-search.html
- 폼 태그의 action 경로 수정
- aria-describdeby 와 p 태그 아이디 일치
- 규칙에 맞게 코드 수정
Resolves #94
- 로그인 페이지 접근성 향상 및 규칙에 맞게 코드 수정
resolves #94
> 💄 Style: 로그인 관련 페이지 수정

- src/components/image-carousel.html
- src/pages/landing-page.html
> 💄Style : 이미지 캐러셀 접근성 관련 코드 수정

- src/components/header.html
- 체크박스 타입으로 헤더에 검색페이지 생성
Resolves #106
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #106
> 🎨 Feat: 헤더에 검색 기능 추가

- src/components/live-ranking-component.html
- src/components/login-button.html
- src/components/login-input.html
- src/components/logout.html
- src/components/modal.html
- 로그인 input, button, 로그아웃, 모달, 실시간 랭킹 컴포넌트 코드 정리
Resolves #101
각 컴포넌트 페이지의 배경 검은색으로 통일
사용하지 않는 기능 정리
보기 편하게 마진 추가
resolves #101
> 💄 Style: 컴포넌트 코드 정리

- index.html
- 주석 오타 수정
- 여백 변경
resolves #118
> 💄 Style: 인덱스 파일 수정

- src/pages/landing-page.html
- src/pages/login.html
- 티빙이라고 적힌 텍스트 타잉으로 수정
Resolves #122
resolves #122
> 💄 Style: 텍스트 수정

- src/pages/id-search-page.html
- src/pages/join-in-page.html
- src/pages/login-page.html
- src/pages/main-page.html
- src/pages/password-search-page.html
- src/pages/profile-edit-page.html
- src/pages/profile-switch-page.html
- 프로필 전환 링크 변경
- 헤더 링크 변경
Resolves #136
resolves #136
> 🐳 Chore: 연결 링크 변경

- src/pages/login-page.html
> 💄 Style: 폼 태그 제출 오류 수정

- src/pages/id-search-page.html
- src/pages/join-in-page.html
- src/pages/password-search-page.html
> 💄 Style: 폼 제출 오류 수정

- src/pages/main-page.html
- 이미지 사이즈 조절(이혼숙려캠프)
resolves #149
> 💄 Style: CSS 등 사용자 UI 디자인 변경

- src/pages/id-search-page.html
- src/pages/join-in-page.html
- src/pages/login-page.html
- src/pages/main-page.html
- src/pages/password-search-page.html
> 이미지 사이즈 에러 해결 후 main 브랜치로 재병합

- src/pages/main-page.html
> 💄style : 메인페이지 이미지에 rouded 부여

- src/pages/main-page.html
> 💄 Style: 이미지 border-radius

- README.md
> 📝 README.md파일에 배포링크 추가

- README.md
> readme.md 오타 수정 

- src/components/live-ranking-component.html
- src/pages/main-page.html
> 💄 Style: 라이브 랭킹 이미지 스크롤 문제 해결

- src/components/header-component.html
- src/pages/main-page.html
> 💄헤더 컴포넌트, 메인 페이지 툴팁 수정

- src/components/header-component.html
- src/pages/main-page.html
> 모바일 가로스크롤 문제 해결

- src/pages/main-page.html
> 💄 Style: 모바일버전 가로스크롤 문제 해결

- src/pages/main-page.html
> 💄 Style: 모바일 스크롤 문제 해결

- src/pages/main-page.html
> 🐛 Fix: 모바일 툴팁 문제

- src/pages/main-page.html
- [] 헤더바 툴팁 메인페이지에 추가
resolves #186
> 💄헤더바 툴팁 메인 페이지에 적용

- src/components/header-component.html
> 💄헤더바 툴팁 모바일 및 hover 수정(컴포넌트)

- src/components/header-component.html
- src/pages/main-page.html
> 헤더바 컴포넌트 및 메인페이지 헤더바 수정

- src/pages/main-page.html
- grid를 flex로 변경합니다
Resolves #194
resolves #194
> 🐛 Fix: 모바일 가로 스크롤 문제 해결

- index.html
- 닫혀 있지 않은 div 태그 -> 닫힌 div 태그 추가
- 중복된 클래스 사용 -> 중복된 class 속성 제거
- ul 태그 내에 li 태그 없이 바로 텍스트 삽입 -> li 태그 추가
- p 태그 안에 블록 태그 nesting -> p 태그 안은 inline 태그로 변경
- 버튼 내부에 div 태그 사용 -> span으로 변경
- font import 에러 -> as="style" 제거
- 짝이 맞지 않은 main 태그 -> 여는 main 태그 추가
resolves #190
> 🐛 fix: 버그, 오류 수정(index.html 파일)

- index.html
- src/pages/main-page.html
> index.html bug 수정 사항 main 브랜치로 병합

- src/components/original-content-component.html
- src/pages/login-page.html
- src/pages/password-search-page.html
- src/pages/profile-edit-page.html
- src/pages/profile-switch-page.html
> 🎉 Init: 타이틀 수정

- src/pages/password-search-page.html
> 비밀번호 찾기 페이지 문법 검사

- src/pages/id-search-page.html
- src/pages/join-in-page.html
- src/pages/login-page.html
> 🐛 Fix: 로그인 관련 페이지 문법 오류 수정

- src/pages/profile-switch-page.html
> 프로필 전환 페이지 문법검사

- src/pages/main-page.html
- 메인 페이지 문법 검사 후 수정
Resolves #203
resolves #203
> 🐛 Fix: 메인 페이지 수정

- src/pages/landing-page.html
- src/pages/main-page.html
> 🐛 Fix: 링크 및 스크립트 수정

- src/pages/profile-edit-page.html
- src/pages/profile-switch-page.html
> 프로필 관련 페이지 수정

- src/pages/landing-page.html
> 💄 Style: 모달 위치 수정
